Contiki 3.x: ieee_15_4_manager Struct Reference
ieee_15_4_manager Struct Reference
Contiki CPUs » AVR » Wireless » RF230 MAC
The interface structure for the 802.15.4 quasi-MAC.
#include <cpu/avr/radio/ieee-manager/ieee-15-4-manager.h>
Data Fields
int(* wake)(void)
Turn the MAC layer on.
int(* sleep)(void)
Turn the MAC layer off.
void(* set_channel)(int channel)
Set the operating channel.
int(* get_channel)(void)
Get the operating channel.
void(* set_dst_panid)(int panid)
Set the Destination PAN_ID.
int(* get_dst_panid)(void)
Get the Destination PAN_ID.
void(* set_src_panid)(int panid)
Set the Source PAN_ID.
int(* get_src_panid)(void)
Get the Source PAN_ID.
void(* set_auto_mode)(bool mode)
Set the Automatic TRX modes.
bool(* get_auto_mode)(void)
Get the current state of Automatic TRX modes.
void(* set_long_addr)(uint64_t address)
Set the Long Address.
uint64_t(* get_long_addr)(void)
Get the Long Address.
void(* set_short_addr)(int address)
Set the Short Address.
int(* get_short_addr)(void)
Get the short Address.
void(* set_iamcoord_bit)(bool iamcoord)
Set the iAmCoord bit.
bool(* get_iamcoord_bit)(void)
Get the iAmCoord bit.
void(* set_coord_long_addr)(uint64_t address)
Set the Coordinator Long address.
uint64_t(* get_coord_long_addr)(void)
Get the Coordinator Long address.
void(* set_coord_short_addr)(int address)
Set the Coordinator Long address.
int(* get_coord_short_addr)(void)
Get the Coordinator Long address.
void(* set_dest_long_addr)(uint64_t address)
Set the Destination address.
uint64_t(* get_dest_long_addr)(void)
Get the Destination address.
Detailed Description
The interface structure for the 802.15.4 quasi-MAC.
Definition at line 53 of file ieee-15-4-manager.h.
Field Documentation
bool(* ieee_15_4_manager::get_auto_mode) (void)
Get the current state of Automatic TRX modes.
Definition at line 77 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
int(* ieee_15_4_manager::get_channel) (void)
Get the operating channel.
Definition at line 62 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
uint64_t(* ieee_15_4_manager::get_coord_long_addr) (void)
Get the Coordinator Long address.
Definition at line 97 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
int(* ieee_15_4_manager::get_coord_short_addr) (void)
Get the Coordinator Long address.
Definition at line 102 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
uint64_t(* ieee_15_4_manager::get_dest_long_addr) (void)
Get the Destination address.
Definition at line 107 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
int(* ieee_15_4_manager::get_dst_panid) (void)
Get the Destination PAN_ID.
Definition at line 67 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init(), and sicslowmac_dataRequest().
bool(* ieee_15_4_manager::get_iamcoord_bit) (void)
Get the iAmCoord bit.
Definition at line 92 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
uint64_t(* ieee_15_4_manager::get_long_addr) (void)
Get the Long Address.
Definition at line 82 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init(), and sicslowmac_dataRequest().
int(* ieee_15_4_manager::get_short_addr) (void)
Get the short Address.
Definition at line 87 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
int(* ieee_15_4_manager::get_src_panid) (void)
Get the Source PAN_ID.
Definition at line 72 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init(), and sicslowmac_dataRequest().
void(* ieee_15_4_manager::set_auto_mode) (bool mode)
Set the Automatic TRX modes.
Definition at line 75 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
void(* ieee_15_4_manager::set_channel) (int channel)
Set the operating channel.
Definition at line 60 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
void(* ieee_15_4_manager::set_coord_long_addr) (uint64_t address)
Set the Coordinator Long address.
Definition at line 95 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
void(* ieee_15_4_manager::set_coord_short_addr) (int address)
Set the Coordinator Long address.
Definition at line 100 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
void(* ieee_15_4_manager::set_dest_long_addr) (uint64_t address)
Set the Destination address.
Definition at line 105 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
void(* ieee_15_4_manager::set_dst_panid) (int panid)
Set the Destination PAN_ID.
Definition at line 65 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
void(* ieee_15_4_manager::set_iamcoord_bit) (bool iamcoord)
Set the iAmCoord bit.
Definition at line 90 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
void(* ieee_15_4_manager::set_long_addr) (uint64_t address)
Set the Long Address.
Definition at line 80 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
void(* ieee_15_4_manager::set_short_addr) (int address)
Set the Short Address.
Definition at line 85 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
void(* ieee_15_4_manager::set_src_panid) (int panid)
Set the Source PAN_ID.
Definition at line 70 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
int(* ieee_15_4_manager::sleep) (void)
Turn the MAC layer off.
Definition at line 57 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().
int(* ieee_15_4_manager::wake) (void)
Turn the MAC layer on.
Definition at line 55 of file ieee-15-4-manager.h.
Referenced by ieee_15_4_init().