Contiki 3.x: rdc_driver Struct Reference
rdc_driver Struct Reference
The structure of a RDC (radio duty cycling) driver in Contiki.
#include <core/net/mac/rdc.h>
Data Fields
void(* init)(void)
Initialize the RDC driver.
void(* send)(mac_callback_t sent_callback, void *ptr)
Send a packet from the Rime buffer.
void(* send_list)(mac_callback_t sent_callback, void *ptr, struct rdc_buf_list *list)
Send a packet list.
void(* input)(void)
Callback for getting notified of incoming packet.
int(* on)(void)
Turn the MAC layer on.
int(* off)(int keep_radio_on)
Turn the MAC layer off.
unsigned short(* channel_check_interval)(void)
Returns the channel check interval, expressed in clock_time_t ticks.
Detailed Description
The structure of a RDC (radio duty cycling) driver in Contiki.
Definition at line 68 of file rdc.h.
Field Documentation
unsigned short(* rdc_driver::channel_check_interval) (void)
Returns the channel check interval, expressed in clock_time_t ticks.
Definition at line 90 of file rdc.h.
Referenced by send_packet().
void(* rdc_driver::input) (void)
Callback for getting notified of incoming packet.
Definition at line 81 of file rdc.h.
int(* rdc_driver::off) (int keep_radio_on)
Turn the MAC layer off.
Definition at line 87 of file rdc.h.
Referenced by send_packet().
int(* rdc_driver::on) (void)
Turn the MAC layer on.
Definition at line 84 of file rdc.h.
Referenced by send_packet().