Contiki 3.x: apps/rest-engine/rest-engine.h File Reference
rest-engine.h File Reference
 An abstraction layer for RESTful Web services (Erbium).
#include <stdio.h>
#include "contiki.h"
#include "contiki-lib.h"
#include "rest-constants.h"
Functions
void rest_init_engine (void)
Initializes REST framework and starts the HTTP or CoAP process.
void rest_activate_resource (resource_t *resource, char *path)
Resources wanted to be accessible should be activated with the following code.
list_t rest_get_resources (void)
Returns the list of registered RESTful resources.
Detailed Description
 An abstraction layer for RESTful Web services (Erbium).
Inspired by RESTful Contiki by Dogan Yazar.
Author
Matthias Kovatsch kovat.nosp@m.sch@.nosp@m.inf.e.nosp@m.thz..nosp@m.ch
Definition in file rest-engine.h.
Function Documentation
void rest_activate_resource (resource_t * resource, char * path)
Resources wanted to be accessible should be activated with the following code.
Parameters
resource A RESTful resource defined through the RESOURCE macros.
path The local URI path where to provide the resource.
Resources wanted to be accessible should be activated with the following code.
Parameters
resource A pointer to a resource implementation
path The URI path string for this resource
The resource implementation must be imported first using the extern keyword. The build system takes care of compiling every *.c file in the ./resources/ sub-directory (see example Makefile).
Definition at line 103 of file rest-engine.c.
References etimer_set(), list_add(), PROCESS_CONTEXT_BEGIN, PROCESS_CONTEXT_END, and process_is_running().
Referenced by PROCESS_THREAD().
list_t rest_get_resources (void)
Returns the list of registered RESTful resources.
Returns
The resource list.
Definition at line 130 of file rest-engine.c.
References etimer_expired(), etimer_reset(), etimer_set(), list_head(), NULL, PROCESS_BEGIN, PROCESS_END, PROCESS_PAUSE, PROCESS_THREAD, and PROCESS_WAIT_EVENT.
void rest_init_engine (void)
Initializes REST framework and starts the HTTP or CoAP process.
Initializes REST framework and starts the HTTP or CoAP process.
This function must be called by server processes before any resources are registered through rest_activate_resource().
Definition at line 71 of file rest-engine.c.
References list_init(), NULL, and process_start().
Referenced by PROCESS_THREAD().