Contiki 3.x: cpu/avr/radio/mac/sicslowmac.h File Reference
sicslowmac.h File Reference
    Example glue code between the existing MAC code and the
    Contiki mac interface
#include <stdbool.h>
#include <stdint.h>
#include "contiki.h"
#include "dev/radio.h"
#include "frame.h"
Functions
uint8_t mac_event_pending (void)
Checks for any pending events in the queue.
void mac_put_event (event_object_t *object)
Puts an event into the queue of events.
event_object_t * mac_get_event (void)
Pulls an event from the event queue.
void mac_task (process_event_t ev, process_data_t data)
This is the main loop task for the MAC.
int sicslowmac_dataRequest (void)
This is the implementation of the 15.4 MAC Data Request primitive.
void sicslowmac_resetRequest (bool setDefaultPIB)
This is the implementation of the 15.4 MAC Reset Request primitive.
Detailed Description
    Example glue code between the existing MAC code and the
    Contiki mac interface
Author
Adam Dunkels adam@.nosp@m.sics.nosp@m..se Eric Gnoske egnos.nosp@m.ke@g.nosp@m.mail..nosp@m.com Blake Leverett bleve.nosp@m.rett.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Definition in file sicslowmac.h.
Function Documentation
uint8_t mac_event_pending (void)
Checks for any pending events in the queue.
Returns
True if there is a pending event, else false.
Definition at line 122 of file sicslowmac.c.
Referenced by mac_task().
event_object_t* mac_get_event (void)
Pulls an event from the event queue.
Assumes that there is an event in the queue. See mac_event_pending().
Returns
Pointer to the event object, or NULL in the event of empty queue.
Definition at line 162 of file sicslowmac.c.
References mac_task(), and NULL.
Referenced by mac_task().
void mac_put_event (event_object_t * object)
Puts an event into the queue of events.
Parameters
object is a pointer to the event to add to queue.
Definition at line 133 of file sicslowmac.c.
Referenced by radio_init(), and rx_frame_parse().
void mac_task (process_event_t ev, process_data_t data)
This is the main loop task for the MAC.
Called by the main application loop.
Definition at line 193 of file sicslowmac.c.
References LSB, mac_event_pending(), mac_get_event(), MSB, packetbuf_clear(), packetbuf_copyfrom(), packetbuf_set_datalen(), and UIP_LLADDR_LEN.
Referenced by mac_get_event(), and PROCESS_THREAD().
int sicslowmac_dataRequest (void)
This is the implementation of the 15.4 MAC Data Request primitive.
Returns
Integer denoting success or failure.
Return values
0 Failure.
1 Success.
        The data request primitive creates the frame header based
        on static and dynamic data. The static data will be refined
        in phase II of the project. The frame payload and length are
        retrieved from the rime buffer and rime length respectively.
        When the header and payload are assembled into the
        frame_create_params structure, the frame is created
        by a call to frame_tx_create and then transmited via
        radio_send_data.
Todo:
For phase 1 the addresses are all long. We'll need a mechanism in the rime attributes to tell the mac to use long or short for phase 2.
Todo:
: Fix delay in sicslowmac so they do not block receiving
Definition at line 396 of file sicslowmac.c.
References fcf_t::ackRequired, addr_t::addr16, addr_t::addr64, frame_create_params_t::dest_addr, frame_create_params_t::dest_pid, fcf_t::destAddrMode, frame_create_params_t::fcf, frame_result_t::frame, frame_tx_create(), fcf_t::framePending, fcf_t::frameType, fcf_t::frameVersion, ieee_15_4_manager::get_dst_panid, ieee_15_4_manager::get_long_addr, ieee_15_4_manager::get_src_panid, frame_result_t::length, macDSN, packetbuf_datalen(), packetbuf_dataptr(), packetbuf_holds_broadcast(), fcf_t::panIdCompression, frame_create_params_t::payload, frame_create_params_t::payload_len, radio_send_data(), RADIO_SUCCESS, RADIO_WRONG_STATE, fcf_t::securityEnabled, frame_create_params_t::seq, frame_create_params_t::src_addr, frame_create_params_t::src_pid, and fcf_t::srcAddrMode.
Referenced by PROCESS_THREAD().
void sicslowmac_resetRequest (bool setDefaultPIB)
This is the implementation of the 15.4 MAC Reset Request primitive.
Parameters
setDefaultPIB True if the default PIB values should be set.
Returns
Integer denoting success or failure.
Return values
0 Failure.
1 Success.
        Sets all PIB values to default.
Todo:
This might be read from the serial eeprom onboard Raven.
Definition at line 559 of file sicslowmac.c.
References AVR_ENTER_CRITICAL_REGION, AVR_LEAVE_CRITICAL_REGION, macCoordShortAddress, macDSN, macDstPANId, macLongAddr, macShortAddress, macSrcPANId, and PROCESS.
Referenced by mac_init().