Contiki 3.x: core/net/mac/tsch/tsch-security.c File Reference
tsch-security.c File Reference
    TSCH security
#include "contiki.h"
#include "net/mac/tsch/tsch.h"
#include "net/mac/tsch/tsch-packet.h"
#include "net/mac/tsch/tsch-private.h"
#include "net/mac/tsch/tsch-schedule.h"
#include "net/mac/tsch/tsch-security.h"
#include "net/mac/tsch/tsch-log.h"
#include "net/mac/frame802154.h"
#include "net/mac/framer-802154.h"
#include "net/netstack.h"
#include "net/packetbuf.h"
#include "lib/ccm-star.h"
#include "lib/aes-128.h"
#include <stdio.h>
#include <string.h>
#include "net/net-debug.h"
Functions
unsigned int tsch_security_mic_len (const frame802154_t *frame)
Return MIC length.
unsigned int tsch_security_secure_frame (uint8_t *hdr, uint8_t *outbuf, int hdrlen, int datalen, struct tsch_asn_t *asn)
Protect a frame with encryption and/or MIC.
unsigned int tsch_security_parse_frame (const uint8_t *hdr, int hdrlen, int datalen, const frame802154_t *frame, const linkaddr_t *sender, struct tsch_asn_t *asn)
Parse and check a frame protected with encryption and/or MIC.
Detailed Description
    TSCH security
Author
Simon Duquennoy simon.nosp@m.duq@.nosp@m.sics..nosp@m.se
Definition in file tsch-security.c.
Function Documentation
unsigned int tsch_security_mic_len (const frame802154_t * frame)
Return MIC length.
Returns
The length of MIC (>= 0)
Definition at line 129 of file tsch-security.c.
References frame802154_t::aux_hdr, frame802154_t::fcf, NULL, frame802154_aux_hdr_t::security_control, frame802154_fcf_t::security_enabled, and frame802154_scf_t::security_level.
Referenced by tsch_radio_off(), tsch_security_parse_frame(), and tsch_security_secure_frame().
unsigned int tsch_security_parse_frame (const uint8_t * hdr, int hdrlen, int datalen, const frame802154_t * frame, const linkaddr_t * sender, struct tsch_asn_t * asn)
Parse and check a frame protected with encryption and/or MIC.
Return values
0 On error or security check failure (insecure frame)
1 On success or no need for security check (good frame)
Definition at line 202 of file tsch-security.c.
References frame802154_t::aux_hdr, frame802154_t::fcf, frame802154_aux_hdr_t::key_index, NULL, frame802154_aux_hdr_t::security_control, frame802154_fcf_t::security_enabled, frame802154_scf_t::security_level, and tsch_security_mic_len().
Referenced by tsch_radio_off().
unsigned int tsch_security_secure_frame (uint8_t * hdr, uint8_t * outbuf, int hdrlen, int datalen, struct tsch_asn_t * asn)
Protect a frame with encryption and/or MIC.
Returns
The length of a generated MIC (>= 0)
Definition at line 139 of file tsch-security.c.
References frame802154_t::aux_hdr, frame802154_t::fcf, frame802154_parse(), frame802154_aux_hdr_t::key_index, linkaddr_node_addr, NULL, frame802154_aux_hdr_t::security_control, frame802154_fcf_t::security_enabled, frame802154_scf_t::security_level, and tsch_security_mic_len().
Referenced by tsch_radio_off().