Contiki 3.x: core/net/mac/tsch/tsch-slot-operation.c File Reference
tsch-slot-operation.c File Reference
    TSCH slot operation implementation, running from interrupt.
#include "contiki.h"
#include "dev/radio.h"
#include "net/netstack.h"
#include "net/packetbuf.h"
#include "net/queuebuf.h"
#include "net/mac/framer-802154.h"
#include "net/mac/tsch/tsch.h"
#include "net/mac/tsch/tsch-slot-operation.h"
#include "net/mac/tsch/tsch-queue.h"
#include "net/mac/tsch/tsch-private.h"
#include "net/mac/tsch/tsch-log.h"
#include "net/mac/tsch/tsch-packet.h"
#include "net/mac/tsch/tsch-security.h"
#include "net/mac/tsch/tsch-adaptive-timesync.h"
#include "net/net-debug.h"
Functions
static void tsch_radio_on (enum tsch_radio_state_on_cmd command)
This function turns on the radio.
static void tsch_radio_off (enum tsch_radio_state_off_cmd command)
This function turns off the radio.
Detailed Description
    TSCH slot operation implementation, running from interrupt.
Author
Simon Duquennoy simon.nosp@m.duq@.nosp@m.sics..nosp@m.se Beshr Al Nahas beshr.nosp@m.@sic.nosp@m.s.se Atis Elsts atis..nosp@m.elst.nosp@m.s@bri.nosp@m.stol.nosp@m..ac.u.nosp@m.k
Definition in file tsch-slot-operation.c.
Function Documentation
static void tsch_radio_off (enum tsch_radio_state_off_cmd command) static
This function turns off the radio.
In the same way as for tsch_radio_on(), it depends on the value of TSCH_RADIO_ON_DURING_TIMESLOT constant:
if enabled, the radio is turned off at the end of the slot
if disabled, the radio is turned off within the slot, directly after Tx'ing or Rx'ing a packet or Tx'ing an ACK.
Definition at line 440 of file tsch-slot-operation.c.
References frame802154_fcf_t::ack_required, frame802154_t::aux_hdr, frame802154_t::fcf, frame802154_parse(), frame802154_fcf_t::frame_type, linkaddr_cmp(), linkaddr_node_addr, linkaddr_null, MAC_TX_COLLISION, MAC_TX_ERR, MAC_TX_NOACK, MAC_TX_OK, NULL, process_poll(), PT_BEGIN, PT_END, PT_SPAWN, PT_THREAD, PT_YIELD, RADIO_RX_MODE_ADDRESS_FILTER, ringbufindex_peek_put(), ringbufindex_put(), RTIMER_NOW, frame802154_aux_hdr_t::security_control, frame802154_scf_t::security_level, frame802154_t::seq, frame802154_t::src_addr, tsch_radio_on(), tsch_security_mic_len(), tsch_security_parse_frame(), and tsch_security_secure_frame().
static void tsch_radio_on (enum tsch_radio_state_on_cmd command) static
This function turns on the radio.
Its semantics is dependent on the value of TSCH_RADIO_ON_DURING_TIMESLOT constant:
if enabled, the radio is turned on at the start of the slot
if disabled, the radio is turned on within the slot, directly before the packet Rx guard time and ACK Rx guard time.
Definition at line 409 of file tsch-slot-operation.c.
Referenced by tsch_radio_off().