Contiki 3.x: core/net/mac/sicslowmac/sicslowmac.c File Reference
sicslowmac.c File Reference
    MAC interface for packaging radio packets into 802.15.4 frames
#include <string.h>
#include "net/mac/sicslowmac/sicslowmac.h"
#include "net/mac/frame802154.h"
#include "net/packetbuf.h"
#include "net/queuebuf.h"
#include "net/netstack.h"
#include "lib/random.h"
Functions
static void send_packet (mac_callback_t sent, void *ptr)
Variables
static uint8_t mac_dsn
The sequence number (0x00 - 0xff) added to the transmitted data or MAC command frame.
static uint16_t mac_dst_pan_id = IEEE802154_PANID
The 16-bit identifier of the PAN on which the device is sending to.
static uint16_t mac_src_pan_id = IEEE802154_PANID
The 16-bit identifier of the PAN on which the device is operating.
Detailed Description
    MAC interface for packaging radio packets into 802.15.4 frames
Author
Adam Dunkels adam@.nosp@m.sics.nosp@m..se Eric Gnoske egnos.nosp@m.ke@g.nosp@m.mail..nosp@m.com Blake Leverett bleve.nosp@m.rett.nosp@m.@gmai.nosp@m.l.co.nosp@m.m Niclas Finne nfi@s.nosp@m.ics..nosp@m.se Joakim Eriksson joaki.nosp@m.me@s.nosp@m.ics.s.nosp@m.e
Definition in file sicslowmac.c.
Function Documentation
static void send_packet (mac_callback_t sent, void * ptr) static
Todo:
For phase 1 the addresses are all long. We'll need a mechanism in the rime attributes to tell the mac to use long or short for phase 2.
Definition at line 97 of file sicslowmac.c.
References frame802154_fcf_t::ack_required, rdc_driver::channel_check_interval, frame802154_t::dest_addr, frame802154_fcf_t::dest_addr_mode, frame802154_t::dest_pid, frame802154_t::fcf, frame802154_create(), frame802154_hdrlen(), frame802154_parse(), frame802154_fcf_t::frame_pending, frame802154_fcf_t::frame_type, frame802154_fcf_t::frame_version, rdc_driver::init, linkaddr_cmp(), linkaddr_copy(), linkaddr_node_addr, mac_dsn, mac_dst_pan_id, mac_src_pan_id, MAC_TX_ERR, MAC_TX_OK, NULL, rdc_driver::off, rdc_driver::on, packetbuf_datalen(), packetbuf_dataptr(), packetbuf_hdralloc(), packetbuf_hdrptr(), packetbuf_hdrreduce(), packetbuf_holds_broadcast(), packetbuf_totlen(), frame802154_fcf_t::panid_compression, frame802154_t::payload, frame802154_t::payload_len, random_rand(), frame802154_fcf_t::security_enabled, rdc_driver::send_list, frame802154_t::seq, frame802154_t::src_addr, frame802154_fcf_t::src_addr_mode, and frame802154_t::src_pid.
Variable Documentation
uint8_t mac_dsn static
The sequence number (0x00 - 0xff) added to the transmitted data or MAC command frame.
The default is a random value within the range.
Definition at line 69 of file sicslowmac.c.
Referenced by send_packet().
uint16_t mac_dst_pan_id = IEEE802154_PANID static
The 16-bit identifier of the PAN on which the device is sending to.
If this value is 0xffff, the device is not associated.
Definition at line 75 of file sicslowmac.c.
Referenced by send_packet().
uint16_t mac_src_pan_id = IEEE802154_PANID static
The 16-bit identifier of the PAN on which the device is operating.
If this value is 0xffff, the device is not associated.
Definition at line 81 of file sicslowmac.c.
Referenced by send_packet().