Contiki 3.x: core/net/mac/framer-802154.c File Reference
framer-802154.c File Reference
    MAC framer for IEEE 802.15.4
#include "net/mac/framer-802154.h"
#include "net/mac/frame802154.h"
#include "net/llsec/llsec802154.h"
#include "net/packetbuf.h"
#include "lib/random.h"
#include <string.h>
Functions
static int create_frame (int type, int do_create)
Variables
static uint8_t mac_dsn
The sequence number (0x00 - 0xff) added to the transmitted data or MAC command frame.
Detailed Description
    MAC framer for IEEE 802.15.4
Author
Niclas Finne nfi@s.nosp@m.ics..nosp@m.se Joakim Eriksson joaki.nosp@m.me@s.nosp@m.ics.s.nosp@m.e
Definition in file framer-802154.c.
Function Documentation
static int create_frame (int type, int do_create) static
Todo:
For phase 1 the addresses are all long. We'll need a mechanism in the rime attributes to tell the mac to use long or short for phase 2.
Definition at line 67 of file framer-802154.c.
References frame802154_fcf_t::ack_required, frame802154_t::aux_hdr, frame802154_t::dest_addr, frame802154_fcf_t::dest_addr_mode, frame802154_t::dest_pid, frame802154_t::fcf, frame802154_create(), frame802154_hdrlen(), frame802154_parse(), frame802154_aux_hdr_t::frame_counter, frame802154_scf_t::frame_counter_size, frame802154_scf_t::frame_counter_suppression, frame802154_fcf_t::frame_pending, frame802154_fcf_t::frame_type, frame802154_fcf_t::frame_version, frame802154_scf_t::key_id_mode, frame802154_aux_hdr_t::key_index, frame802154_aux_hdr_t::key_source, linkaddr_copy(), mac_dsn, packetbuf_datalen(), packetbuf_dataptr(), packetbuf_hdralloc(), packetbuf_hdrptr(), packetbuf_hdrreduce(), packetbuf_holds_broadcast(), packetbuf_totlen(), frame802154_fcf_t::panid_compression, frame802154_t::payload, frame802154_t::payload_len, random_rand(), frame802154_aux_hdr_t::security_control, frame802154_fcf_t::security_enabled, frame802154_scf_t::security_level, frame802154_t::seq, frame802154_fcf_t::sequence_number_suppression, frame802154_t::src_addr, frame802154_fcf_t::src_addr_mode, and frame802154_t::src_pid.
Variable Documentation
uint8_t mac_dsn static
The sequence number (0x00 - 0xff) added to the transmitted data or MAC command frame.
The default is a random value within the range.
Definition at line 61 of file framer-802154.c.
Referenced by create_frame().