Contiki 3.x: cpu/arm/aducrf101/Common/system_ADuCRF101.h File Reference
system_ADuCRF101.h File Reference
Copyright (c) 2014, Analog Devices, Inc.
Functions
void SystemInit (void)
Initialize the system.
void SystemCoreClockUpdate (void)
Update internal SystemCoreClock variable.
void SetSystemExtClkFreq (uint32_t ExtClkFreq)
Sets the system external clock frequency.
uint32_t GetSystemExtClkFreq (void)
Gets the system external clock frequency.
Detailed Description
Copyright (c) 2014, Analog Devices, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Analog Devices, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
: CMSIS Cortex-M3 Device Peripheral Access Layer Header File for the ADuCRF101
Version
v0.2
Author
PAD CSE group, Analog Devices Inc
Date
March 09th 2012
Definition in file system_ADuCRF101.h.
Function Documentation
uint32_t GetSystemExtClkFreq (void)
Gets the system external clock frequency.
Returns
External Clock frequency
Gets the clock frequency of the source connected to P0.5 clock input source
Definition at line 146 of file system_ADuCRF101.c.
References __disable_irq(), __enable_irq(), and SystemCoreClockUpdate().
void SetSystemExtClkFreq (uint32_t ExtClkFreq)
Sets the system external clock frequency.
Parameters
ExtClkFreq External clock frequency in Hz
Returns
none
Sets the clock frequency of the source connected to P0.5 clock input source
Definition at line 134 of file system_ADuCRF101.c.
void SystemCoreClockUpdate (void)
Update internal SystemCoreClock variable.
Returns
none
Updates the internal SystemCoreClock with current core Clock retrieved from cpu registers.
Definition at line 71 of file system_ADuCRF101.c.
Referenced by GetSystemExtClkFreq(), and SystemInit().
void SystemInit (void)
Initialize the system.
Returns
none
Setup the microcontroller system. Initialize the System and update the SystemCoreClock variable.
Returns
none
Setup the microcontroller system. Initialize the System and update the SystemFrequency variable.
Definition at line 114 of file system_ADuCRF101.c.
References SystemCoreClockUpdate().