Contiki 3.x: cpu/avr/dev/usb/usb_specific_request.c File Reference
usb_specific_request.c File Reference
USB Protocol-Specific Requests.
#include "radio.h"
#include "contiki.h"
#include "config.h"
#include "usb_drv.h"
#include "usb_descriptors.h"
#include "usb_specific_request.h"
#include "rndis/rndis_protocol.h"
#include "rndis/cdc_ecm.h"
#include "rndis/rndis_task.h"
#include "serial/uart_usb_lib.h"
#include "storage/ctrl_access.h"
#include "uip.h"
#include <avr/pgmspace.h>
#include <avr/eeprom.h>
#include <string.h>
Functions
Bool usb_user_read_request (U8 type, U8 request)
This function is called by the standard usb read request function when the Usb request is not supported.
Bool usb_user_get_descriptor (U8 type, U8 string)
usb_user_get_descriptor.
void usb_user_endpoint_init (U8 conf_nb)
usb_user_endpoint_init.
Detailed Description
USB Protocol-Specific Requests.
Definition in file usb_specific_request.c.
Function Documentation
void usb_user_endpoint_init (U8 conf_nb)
usb_user_endpoint_init.
This function configures the endpoints.
Parameters
conf_nb Not used
Definition at line 315 of file usb_specific_request.c.
References FALSE, TRUE, Usb_ack_receive_out, Usb_ack_receive_setup, usb_configuration_nb, Usb_read_byte, Usb_reset_endpoint, Usb_send_control_in, and Usb_write_byte.
Referenced by usb_set_configuration().
Bool usb_user_get_descriptor (U8 type, U8 string)
usb_user_get_descriptor.
This function returns the size and the pointer on a user information structure
Parameters
type descriptor type
string descriptor ID
Return values
FALSE
Definition at line 200 of file usb_specific_request.c.
References S_usb_language_id::bLength, FALSE, NULL, and TRUE.
Referenced by usb_get_descriptor().
Bool usb_user_read_request (U8 type, U8 request)
This function is called by the standard usb read request function when the Usb request is not supported.
This function returns TRUE when the request is processed. This function returns FALSE if the request is not supported. In this case, a STALL handshake will be automatically sent by the standard usb read request function.
Parameters
type Not used
request Read request type
Return values
FALSE if unknown read type
TRUE if request type is processed
Definition at line 89 of file usb_specific_request.c.
References FALSE, get_nb_lun(), LSB, MSB, rndis_get_encapsulated_command(), rndis_send_encapsulated_command(), TRUE, Usb_ack_receive_setup, usb_configuration_nb, Usb_read_byte, Usb_send_control_in, and Usb_write_byte.
Referenced by usb_process_request().