Contiki 3.x: cpu/avr/dev/usb/usb_standard_request.h File Reference
usb_standard_request.h File Reference
This file contains the USB endpoint 0 management routines corresponding to the standard enumeration process (refer to chapter 9 of the USB specification. This file calls routines of the usb_specific_request.c file for non-standard request management. The enumeration parameters (descriptor tables) are contained in the usb_descriptors.c file.
#include "usb_task.h"
#include "usb_descriptors.h"
Macros
#define Is_device_enumerated() ((usb_configuration_nb!=0) ? TRUE : FALSE)
Returns true when device connected and correctly enumerated with an host.
Functions
void usb_process_request (void)
usb_process_request.
Detailed Description
This file contains the USB endpoint 0 management routines corresponding to the standard enumeration process (refer to chapter 9 of the USB specification. This file calls routines of the usb_specific_request.c file for non-standard request management. The enumeration parameters (descriptor tables) are contained in the usb_descriptors.c file.
Definition in file usb_standard_request.h.
Macro Definition Documentation
#define Is_device_enumerated () ((usb_configuration_nb!=0) ? TRUE : FALSE)
Returns true when device connected and correctly enumerated with an host.
The device high level application should tests this before performing any applicative requests
Definition at line 78 of file usb_standard_request.h.
Referenced by PROCESS_THREAD(), tx_end_led(), and usb_eth_send().
Function Documentation
void usb_process_request (void)
usb_process_request.
This function reads the SETUP request sent to the default control endpoint and calls the appropriate function. When exiting of the usb_read_request function, the device is ready to manage the next request.
Note
list of supported requests: GET_DESCRIPTOR GET_CONFIGURATION SET_ADDRESS SET_CONFIGURATION CLEAR_FEATURE SET_FEATURE GET_STATUS
< un-supported request => call to user read request
Definition at line 118 of file usb_standard_request.c.
References CLEAR_FEATURE, Is_usb_receive_setup, SET_FEATURE, Usb_ack_in_ready, Usb_ack_receive_out, Usb_ack_receive_setup, usb_clear_feature(), Usb_enable_stall_handshake, usb_get_configuration(), usb_get_descriptor(), usb_get_interface(), usb_get_status(), Usb_read_byte, Usb_select_endpoint, usb_set_address(), usb_set_configuration(), usb_set_feature(), usb_set_interface(), and usb_user_read_request().
Referenced by pollhandler(), and usb_mass_storage_csw().