Contiki 3.x: cpu/cc253x/dev/cc2530-rf.c File Reference
cc2530-rf.c File Reference
    Implementation of the cc2530 RF driver
#include "contiki.h"
#include "dev/radio.h"
#include "dev/cc2530-rf.h"
#include "cc253x.h"
#include "sfr-bits.h"
#include "sys/clock.h"
#include "sys/rtimer.h"
#include "net/packetbuf.h"
#include "net/rime/rimestats.h"
#include "net/linkaddr.h"
#include "net/netstack.h"
#include <string.h>
Functions
static uint8_t get_channel ()
Get the current operating channel.
static int8_t set_channel (uint8_t channel)
Set the current operating channel.
static radio_value_t get_rssi (void)
Reads the current signal strength (RSSI)
Detailed Description
    Implementation of the cc2530 RF driver
Author
George Oikonomou - oikon.nosp@m.omou.nosp@m.@user.nosp@m.s.so.nosp@m.urcef.nosp@m.orge.nosp@m..net
Definition in file cc2530-rf.c.
Function Documentation
static uint8_t get_channel (void) static
Get the current operating channel.
Returns
Returns a value in [11,26] representing the current channel
Definition at line 153 of file cc2530-rf.c.
Referenced by get_rssi().
static radio_value_t get_rssi (void) static
Reads the current signal strength (RSSI)
Returns
The current RSSI in dBm
This function reads the current RSSI on the currently configured channel.
Definition at line 217 of file cc2530-rf.c.
References radio_driver::channel_clear, clock_delay_usec(), get_channel(), radio_driver::get_object, radio_driver::get_value, radio_driver::off, radio_driver::on, radio_driver::pending_packet, radio_driver::prepare, RADIO_RX_MODE_ADDRESS_FILTER, radio_driver::read, radio_driver::receiving_packet, RTIMER_NOW, radio_driver::send, set_channel(), radio_driver::set_object, radio_driver::set_value, and radio_driver::transmit.
static int8_t set_channel (uint8_t channel) static
Set the current operating channel.
Parameters
channel The desired channel as a value in [11,26]
Returns
Returns a value in [11,26] representing the current channel or a negative value if channel was out of bounds
Definition at line 165 of file cc2530-rf.c.
References addr.
Referenced by get_rssi().