Contiki 3.x: EEPROM API
EEPROM API
Device driver APIs
The EEPROM API defines a common interface for EEPROM access on Contiki platforms.
Functions
void eeprom_write (eeprom_addr_t addr, unsigned char *buf, int size)
Write a buffer into EEPROM.
void eeprom_read (eeprom_addr_t addr, unsigned char *buf, int size)
Read data from the EEPROM.
void eeprom_init (void)
Initialize the EEPROM module.
Detailed Description
The EEPROM API defines a common interface for EEPROM access on Contiki platforms.
A platform with EEPROM support must implement this API.
Function Documentation
void eeprom_init (void)
Initialize the EEPROM module.
This function initializes the EEPROM module and is called from the bootup code.
Initialize the EEPROM module.
Definition at line 72 of file eeprom.c.
Referenced by main().
void eeprom_read (eeprom_addr_t addr, unsigned char * buf, int size)
Read data from the EEPROM.
This function reads a number of bytes from the specified address in EEPROM and into a buffer in memory.
Parameters
addr The address in EEPROM from which the data should be read.
buf A pointer to the buffer to which the data should be stored.
size The number of bytes to read.
Read data from the EEPROM.
Parameters
addr The eeprom memory address
buf It is the destination buffer in witch the bytes will be written
size It is the number of byte to read
Definition at line 49 of file eeprom.c.
References addr, eeprom_init(), and i2c_read().
Referenced by cfs_read().
void eeprom_write (eeprom_addr_t addr, unsigned char * buf, int size)
Write a buffer into EEPROM.
This function writes a buffer of the specified size into EEPROM.
Parameters
addr The address in EEPROM to which the buffer should be written.
buf A pointer to the buffer from which data is to be read.
size The number of bytes to write into EEPROM.
Write a buffer into EEPROM.
Parameters
addr The eeprom memory address
buf It is the buffer of bytes that will be written to the eeprom
size It is the number of byte to write
Definition at line 42 of file eeprom.c.
References addr, and eeprom_init().
Referenced by cfs_write().