Contiki 3.x: An implementation of OMA LWM2M
An implementation of OMA LWM2M
Applications
This application is an implementation of OMA Lightweight M2M.
Files
file ipso-objects.c
    Implementation of the IPSO Objects
file lwm2m-device.c
    Implementation of the Contiki OMA LWM2M device
file lwm2m-device.h
    Header file for the Contiki OMA LWM2M device
file lwm2m-engine.c
    Implementation of the Contiki OMA LWM2M engine
file lwm2m-engine.h
    Header file for the Contiki OMA LWM2M engine
file lwm2m-json.c
    Implementation of the Contiki OMA LWM2M JSON writer
file lwm2m-json.h
    Header file for the Contiki OMA LWM2M JSON writer
file lwm2m-object.c
    Implementation of the Contiki OMA LWM2M object API
file lwm2m-object.h
    Header file for the Contiki OMA LWM2M object API
file lwm2m-plain-text.c
    Implementation of the Contiki OMA LWM2M plain text reader / writer
file lwm2m-plain-text.h
    Header file for the Contiki OMA LWM2M plain text reader / writer
file lwm2m-security.c
    Implementation of the Contiki OMA LWM2M security
file lwm2m-server.c
    Implementation of the Contiki OMA LWM2M server
file oma-tlv-reader.c
    Implementation of the Contiki OMA LWM2M TLV reader
file oma-tlv-reader.h
    Header file for the Contiki OMA LWM2M TLV reader
file oma-tlv-writer.c
    Implementation of the Contiki OMA LWM2M TLV writer
file oma-tlv-writer.h
    Header file for the Contiki OMA LWM2M TLV writer
file oma-tlv.c
    Implementation of the Contiki OMA LWM2M TLV
file oma-tlv.h
    Header file for the Contiki OMA LWM2M TLV
Functions
void lwm2m_device_init (void)
void lwm2m_security_init (void)
void lwm2m_server_init (void)
PROCESS_THREAD (lwm2m_rd_client, ev, data)
static int write_object_instances_link (const lwm2m_object_t *object, char *buffer, size_t size)
Write a list of object instances as a CoRE Link-format list.
static unsigned int lwm2m_engine_select_writer (lwm2m_context_t *context, unsigned int accept)
Set the writer pointer to the proper writer based on the Accept: header.
static void lwm2m_engine_select_reader (lwm2m_context_t *context, unsigned int content_format)
Set the reader pointer to the proper reader based on the Content-format: header.
Detailed Description
This application is an implementation of OMA Lightweight M2M.
Function Documentation
void lwm2m_device_init (void)
Register this device and its handlers - the handlers automatically sends in the object to handle.
Definition at line 142 of file lwm2m-device.c.
Referenced by PROCESS_THREAD().
static void lwm2m_engine_select_reader (lwm2m_context_t * context, unsigned int content_format) static
Set the reader pointer to the proper reader based on the Content-format: header.
Parameters
[in] context LWM2M context to operate on
[in] content_format Content-type type number from CoAP headers
Definition at line 786 of file lwm2m-engine.c.
References accept(), context, lwm2m_engine_select_writer(), NULL, and write_object_instances_link().
static unsigned int lwm2m_engine_select_writer (lwm2m_context_t * context, unsigned int accept) static
Set the writer pointer to the proper writer based on the Accept: header.
Parameters
[in] context LWM2M context to operate on
[in] accept Accept type number from CoAP headers
Returns
The content type of the response if the selected writer is used
Definition at line 755 of file lwm2m-engine.c.
References accept().
Referenced by lwm2m_engine_select_reader().
void lwm2m_security_init (void)
Register this device and its handlers - the handlers automatically sends in the object to handle.
Definition at line 93 of file lwm2m-security.c.
Referenced by PROCESS_THREAD().
void lwm2m_server_init (void)
Register this device and its handlers - the handlers automatically sends in the object to handle
Definition at line 74 of file lwm2m-server.c.
Referenced by PROCESS_THREAD().
PROCESS_THREAD (lwm2m_rd_client , ev , data)
Secure CoAP should use a different port but for now the same port is used.
Definition at line 248 of file lwm2m-engine.c.
References addr, ADDR_TENTATIVE, CLOCK_SECOND, context, etimer_expired(), etimer_set(), ipaddr, lwm2m_device_init(), lwm2m_security_init(), lwm2m_server_init(), NULL, PROCESS_BEGIN, PROCESS_END, process_start(), PROCESS_YIELD, rest_activate_resource(), rest_init_engine(), start(), uip_ds6_if, UIP_HTONS, and uiplib_ipaddrconv.