Contiki 3.x: Link estimate management
Link estimate management
Communication stacks » The Rime communication stack
The link estimate module is used for computing estimations of link quality.
Functions
void collect_link_estimate_new (struct collect_link_estimate *le)
Initialize a new link estimate.
void collect_link_estimate_update_tx (struct collect_link_estimate *le, uint8_t tx)
Update a link estimate when a packet has been sent.
void collect_link_estimate_update_tx_fail (struct collect_link_estimate *le, uint8_t tx)
Update a link estimate when a packet has failed to be sent.
void collect_link_estimate_update_rx (struct collect_link_estimate *n)
Update a link estimate when a packet has been received.
uint16_t collect_link_estimate (struct collect_link_estimate *le)
Compute the link estimate metric for a link estimate.
Detailed Description
The link estimate module is used for computing estimations of link quality.
It computes a quality index for links, based on information about how many times a packet has been transmitted, as well as information about incoming packets. The link estimate module exposes an interface that provides functions that are called for incoming and outgoing packets.
Function Documentation
uint16_t collect_link_estimate (struct collect_link_estimate * le)
Compute the link estimate metric for a link estimate.
Parameters
le A pointer to a link estimate structure
Returns
The current link estimate metric
Definition at line 118 of file collect-link-estimate.c.
References collect_link_estimate(), and NULL.
Referenced by collect_link_estimate().
void collect_link_estimate_new (struct collect_link_estimate * le)
Initialize a new link estimate.
Parameters
le A pointer to a link estimate structure
        This function initializes a link estimate.
Definition at line 64 of file collect-link-estimate.c.
References NULL.
void collect_link_estimate_update_rx (struct collect_link_estimate * le)
Update a link estimate when a packet has been received.
Parameters
le A pointer to a link estimate structure
        This function updates a link estimate. This function is
        called when a packet has been received. The function
        uses information from the packet buffer and its
        attributes.
Definition at line 112 of file collect-link-estimate.c.
void collect_link_estimate_update_tx (struct collect_link_estimate * le, uint8_t num_tx)
Update a link estimate when a packet has been sent.
Parameters
le A pointer to a link estimate structure
num_tx The number of times the packet was transmitted before it was ACKed
        This function updates a link estimate. This function is
        called when a packet has been sent. The function may
        use information from the packet buffer and the packet
        buffer attributes when computing the link estimate.
Definition at line 74 of file collect-link-estimate.c.
References NULL.
Referenced by collect_link_estimate_update_tx_fail().
void collect_link_estimate_update_tx_fail (struct collect_link_estimate * le, uint8_t num_tx)
Update a link estimate when a packet has failed to be sent.
Parameters
le A pointer to a link estimate structure
num_tx The number of times the packet was transmitted before it was given up on.
        This function updates a link estimate. This function is
        called when a packet has been sent. The function may
        use information from the packet buffer and the packet
        buffer attributes when computing the link estimate.
Definition at line 102 of file collect-link-estimate.c.
References collect_link_estimate_update_tx(), and NULL.