Contiki 3.x: uIP initialization functions
uIP initialization functions
Communication stacks » The uIP TCP/IP stack
The uIP initialization functions are used for booting uIP.
Functions
void uip_init (void)
uIP initialization function.
void uip_setipid (uint16_t id)
uIP initialization function.
Detailed Description
The uIP initialization functions are used for booting uIP.
Function Documentation
void uip_init (void)
uIP initialization function.
This function should be called at boot up to initilize the uIP TCP/IP stack.
Definition at line 363 of file uip.c.
References uip_mcast6_driver::init, uip_conn::initialmss, uip_conn::len, uip_conn::lport, uip_udp_conn::lport, uip_conn::mss, uip_conn::nrtx, uip_conn::rcv_nxt, uip_conn::ripaddr, uip_conn::rport, uip_conn::rto, uip_conn::sa, uip_conn::snd_nxt, uip_conn::sv, uip_conn::tcpstateflags, uip_conn::timer, uip_connect(), UIP_CONNS, uip_ds6_init(), uip_ext_len, uip_htons(), uip_icmp6_init(), UIP_IP_BUF, uip_ipaddr_copy, uip_len, UIP_LISTENPORTS, uip_nd6_init(), UIP_RTO, UIP_TCP_MSS, and UIP_UDP_CONNS.
Referenced by main(), tcpip_poll_tcp(), and uip_log().
void uip_setipid (uint16_t id)
uIP initialization function.
This function may be used at boot time to set the initial ip_id.
Definition at line 162 of file uip.c.