Contiki 3.x: Rime buffer management
Rime buffer management
Communication stacks » The Rime communication stack
The packetbuf module does Rime's buffer management.
Macros
#define PACKETBUF_SIZE 128
The size of the packetbuf, in bytes.
Functions
void packetbuf_clear (void)
Clear and reset the packetbuf.
int packetbuf_copyfrom (const void *from, uint16_t len)
Copy from external data into the packetbuf.
void packetbuf_compact (void)
Compact the packetbuf.
int packetbuf_copyto (void *to)
Copy the entire packetbuf to an external buffer.
int packetbuf_hdralloc (int size)
Extend the header of the packetbuf, for outbound packets.
int packetbuf_hdrreduce (int size)
Reduce the header in the packetbuf, for incoming packets.
void packetbuf_set_datalen (uint16_t len)
Set the length of the data in the packetbuf.
void * packetbuf_dataptr (void)
Get a pointer to the data in the packetbuf.
void * packetbuf_hdrptr (void)
Get a pointer to the header in the packetbuf, for outbound packets.
uint16_t packetbuf_datalen (void)
Get the length of the data in the packetbuf.
uint8_t packetbuf_hdrlen (void)
Get the length of the header in the packetbuf.
uint16_t packetbuf_totlen (void)
Get the total length of the header and data in the packetbuf.
uint16_t packetbuf_remaininglen (void)
Get the total length of the remaining space in the packetbuf.
int packetbuf_holds_broadcast (void)
Checks whether the current packet is a broadcast.
Detailed Description
The packetbuf module does Rime's buffer management.
Function Documentation
void packetbuf_clear (void)
Clear and reset the packetbuf.
This function clears the packetbuf and resets all internal state pointers (header size, header pointer, external data pointer). It is used before preparing a packet in the packetbuf.
Examples:
example-collect.c.
Definition at line 76 of file packetbuf.c.
Referenced by mac_task(), main(), mrf24j40_init(), output(), packetbuf_copyfrom(), PROCESS_THREAD(), retransmit_current_packet(), rf_core_primary_mode_restore(), ST_RadioDataPendingLongIdIsrCallback(), and update_rtmetric().
void packetbuf_compact (void)
Compact the packetbuf.
This function compacts the packetbuf by copying the data portion of the packetbuf so that becomes consecutive to the header.
This function is called by the Rime code before a packet is to be sent by a device driver. This assures that the entire packet is consecutive in memory.
Definition at line 97 of file packetbuf.c.
References packetbuf_hdrlen().
int packetbuf_copyfrom (const void * from, uint16_t len)
Copy from external data into the packetbuf.
Parameters
from A pointer to the data from which to copy
len The size of the data to copy
Return values
The number of bytes that was copied into the packetbuf
        This function copies data from a pointer into the
        packetbuf. If the data that is to be copied is larger
        than the packetbuf, only the data that fits in the
        packetbuf is copied. The number of bytes that could be
        copied into the rimbuf is returned.
Examples:
example-broadcast.c, example-mesh.c, example-multihop.c, example-runicast.c, example-trickle.c, and example-unicast.c.
Definition at line 85 of file packetbuf.c.
References packetbuf_clear(), and PACKETBUF_SIZE.
Referenced by ble_mac_ipsp_evt_handler_irq(), and mac_task().
int packetbuf_copyto (void * to)
Copy the entire packetbuf to an external buffer.
Parameters
to A pointer to the buffer to which the data is to be copied
Return values
The number of bytes that was copied to the external buffer
        This function copies the packetbuf to an external
        buffer. Both the data portion and the header portion of
        the packetbuf is copied.
        The external buffer to which the packetbuf is to be
        copied must be able to accomodate at least
        PACKETBUF_SIZE bytes. The number of
        bytes that was copied to the external buffer is
        returned.
Definition at line 111 of file packetbuf.c.
References packetbuf_dataptr(), packetbuf_hdrptr(), and PACKETBUF_SIZE.
uint16_t packetbuf_datalen (void)
Get the length of the data in the packetbuf.
Returns
Length of the data in the packetbuf
Examples:
example-collect.c, and example-mesh.c.
Definition at line 170 of file packetbuf.c.
Referenced by create_frame(), input(), packetbuf_totlen(), retransmit_current_packet(), send_packet(), send_to_peer(), sicslowmac_dataRequest(), and uncompress_hdr_iphc().
void * packetbuf_dataptr (void)
Get a pointer to the data in the packetbuf.
Returns
Pointer to the packetbuf data
        This function is used to get a pointer to the data in
        the packetbuf. The data is either stored in the packetbuf,
        or referenced to an external location.
Examples:
example-broadcast.c, example-collect.c, example-mesh.c, example-multihop.c, and example-trickle.c.
Definition at line 158 of file packetbuf.c.
References packetbuf_hdrlen().
Referenced by create_frame(), input(), main(), mrf24j40_init(), output(), packetbuf_copyto(), PROCESS_THREAD(), retransmit_current_packet(), rf_core_primary_mode_restore(), send_packet(), send_queued_packet(), send_to_peer(), sicslowmac_dataRequest(), and ST_RadioDataPendingLongIdIsrCallback().
int packetbuf_hdralloc (int size)
Extend the header of the packetbuf, for outbound packets.
Parameters
size The number of bytes the header should be extended
Return values
Non-zero if the header could be extended, zero otherwise
        This function is used to allocate extra space in the
        header portion in the packetbuf, when preparing outbound
        packets for transmission. If the function is unable to
        allocate sufficient header space, the function returns
        zero and does not allocate anything.
Definition at line 122 of file packetbuf.c.
References PACKETBUF_SIZE, and packetbuf_totlen().
Referenced by create_frame(), retransmit_callback(), send_packet(), and update_rtmetric().
uint8_t packetbuf_hdrlen (void)
Get the length of the header in the packetbuf.
Returns
Length of the header in the packetbuf
Definition at line 176 of file packetbuf.c.
Referenced by packetbuf_compact(), packetbuf_dataptr(), and packetbuf_totlen().
void * packetbuf_hdrptr (void)
Get a pointer to the header in the packetbuf, for outbound packets.
Returns
Pointer to the packetbuf header
Definition at line 164 of file packetbuf.c.
Referenced by create_frame(), main(), packetbuf_copyto(), and send_packet().
int packetbuf_hdrreduce (int size)
Reduce the header in the packetbuf, for incoming packets.
Parameters
size The number of bytes the header should be reduced
Return values
Non-zero if the header could be reduced, zero otherwise
        This function is used to remove the first part of the
        header in the packetbuf, when processing incoming
        packets. If the function is unable to remove the
        requested amount of header space, the function returns
        zero and does not allocate anything.
Definition at line 139 of file packetbuf.c.
Referenced by create_frame(), retransmit_current_packet(), and send_packet().
int packetbuf_holds_broadcast (void)
Checks whether the current packet is a broadcast.
Return values
0 iff current packet is not a broadcast
Definition at line 248 of file packetbuf.c.
References addr, linkaddr_cmp(), and linkaddr_null.
Referenced by create_frame(), mac_LowpanToEthernet(), send_packet(), sicslowmac_dataRequest(), and slide().
uint16_t packetbuf_remaininglen (void)
Get the total length of the remaining space in the packetbuf.
Returns
Length of the remaining space in the packetbuf
Definition at line 188 of file packetbuf.c.
References addr, linkaddr_copy(), linkaddr_null, PACKETBUF_SIZE, and packetbuf_totlen().
void packetbuf_set_datalen (uint16_t len)
Set the length of the data in the packetbuf.
Parameters
len The length of the data
Examples:
example-collect.c.
Definition at line 151 of file packetbuf.c.
Referenced by mac_task(), main(), mrf24j40_init(), output(), PROCESS_THREAD(), retransmit_current_packet(), rf_core_primary_mode_restore(), and ST_RadioDataPendingLongIdIsrCallback().
uint16_t packetbuf_totlen (void)
Get the total length of the header and data in the packetbuf.
Returns
Length of data and header in the packetbuf
Definition at line 182 of file packetbuf.c.
References packetbuf_datalen(), and packetbuf_hdrlen().
Referenced by create_frame(), packetbuf_hdralloc(), packetbuf_remaininglen(), and send_packet().