Contiki 3.x: Callback timer
Callback timer
Contiki system
The ctimer module provides a timer mechanism that calls a specified C function when a ctimer expires.
Functions
void ctimer_init (void)
Initialize the callback timer library.
void ctimer_set (struct ctimer *c, clock_time_t t, void(*f)(void *), void *ptr)
Set a callback timer.
void ctimer_set_with_process (struct ctimer *c, clock_time_t t, void(*f)(void *), void *ptr, struct process *p)
Set a callback timer.
void ctimer_reset (struct ctimer *c)
Reset a callback timer with the same interval as was previously set.
void ctimer_restart (struct ctimer *c)
Restart a callback timer from the current point in time.
void ctimer_stop (struct ctimer *c)
Stop a pending callback timer.
int ctimer_expired (struct ctimer *c)
Check if a callback timer has expired.
Detailed Description
The ctimer module provides a timer mechanism that calls a specified C function when a ctimer expires.
Function Documentation
int ctimer_expired (struct ctimer * c)
Check if a callback timer has expired.
Parameters
c A pointer to the callback timer
Returns
Non-zero if the timer has expired, zero otherwise.
        This function tests if a callback timer has expired and
        returns true or false depending on its status.
Definition at line 161 of file ctimer.c.
References etimer_expired(), list_head(), and NULL.
void ctimer_init (void)
Initialize the callback timer library.
This function initializes the callback timer library and should be called from the system boot up code.
Definition at line 91 of file ctimer.c.
References list_init(), NULL, and process_start().
Referenced by main(), and uip_log().
void ctimer_reset (struct ctimer * c)
Reset a callback timer with the same interval as was previously set.
Parameters
c A pointer to the callback timer.
        This function resets the callback timer with the same
        interval that was given to the callback timer with the
        ctimer_set() function. The start point of the interval
        is the exact time that the callback timer last
        expired. Therefore, this function will cause the timer
        to be stable over time, unlike the ctimer_restart()
        function.
See also
ctimer_restart()
Definition at line 125 of file ctimer.c.
References etimer_reset(), list_add(), PROCESS_CONTEXT_BEGIN, and PROCESS_CONTEXT_END.
Referenced by stbroadcast_open().
void ctimer_restart (struct ctimer * c)
Restart a callback timer from the current point in time.
Parameters
c A pointer to the callback timer.
        This function restarts the callback timer with the same
        interval that was given to the ctimer_set()
        function. The callback timer will start at the current
        time.
        \note A periodic timer will drift if this function is
        used to reset it. For periodic timers, use the
        ctimer_reset() function instead.
See also
ctimer_reset()
Definition at line 137 of file ctimer.c.
References etimer_restart(), list_add(), PROCESS_CONTEXT_BEGIN, and PROCESS_CONTEXT_END.
void ctimer_set (struct ctimer * c, clock_time_t t, void(*)(void *) f, void * ptr)
Set a callback timer.
Parameters
c A pointer to the callback timer.
t The interval before the timer expires.
f A function to be called when the timer expires.
ptr An opaque pointer that will be supplied as an argument to the callback function.
        This function is used to set a callback timer for a time
        sometime in the future. When the callback timer expires,
        the callback function f will be called with ptr as argument.
        This essentially does ctimer_set_process(c, t, f, ptr, PROCESS_CURRENT());
Examples:
example-multihop.c.
Definition at line 99 of file ctimer.c.
References ctimer_set_with_process(), and PROCESS_CURRENT.
Referenced by btn_callback(), configure(), gyro_convert(), ipolite_send(), packetqueue_enqueue_packetbuf(), polite_send(), retransmit_callback(), retransmit_current_packet(), rf_cmd_ieee_rx(), select_on_bus(), send_queued_packet(), stbroadcast_set_timer(), uart0_set_input(), and update_rtmetric().
void ctimer_set_with_process (struct ctimer * c, clock_time_t t, void(*)(void *) f, void * ptr, struct process * p)
Set a callback timer.
Parameters
c A pointer to the callback timer.
t The interval before the timer expires.
f A function to be called when the timer expires.
ptr An opaque pointer that will be supplied as an argument to the callback function.
p A pointer to the process the timer belongs to
        This function is used to set a callback timer for a time
        sometime in the future. When the callback timer expires,
        the callback function f will be called with ptr as argument.
Definition at line 106 of file ctimer.c.
References etimer_set(), list_add(), PROCESS_CONTEXT_BEGIN, and PROCESS_CONTEXT_END.
Referenced by ctimer_set().
void ctimer_stop (struct ctimer * c)
Stop a pending callback timer.
Parameters
c A pointer to the pending callback timer.
        This function stops a callback timer that has previously
        been set with ctimer_set(), ctimer_reset(), or ctimer_restart().
        After this function has been called, the callback timer will be
        expired and will not call the callback function.
Definition at line 149 of file ctimer.c.
References etimer_stop(), list_remove(), and NULL.
Referenced by btn_callback(), configure(), ipolite_cancel(), ipolite_close(), ipolite_send(), packetqueue_dequeue(), packetqueue_init(), polite_cancel(), polite_close(), retransmit_callback(), retransmit_current_packet(), stbroadcast_cancel(), and stbroadcast_open().