Contiki 3.x: General configuration options
General configuration options
Communication stacks » The uIP TCP/IP stack » Configuration options for uIP
Macros
#define UIP_LLH_LEN
The link level header length.
#define UIP_BUFSIZE
The size of the uIP packet buffer.
#define UIP_STATISTICS 0
Determines if statistics support should be compiled in.
#define UIP_LOGGING
Determines if logging of certain events should be compiled in.
#define UIP_BROADCAST
Broadcast support.
Functions
void uip_log (char *msg)
Print out a uIP log message.
Detailed Description
Macro Definition Documentation
#define UIP_BROADCAST
Broadcast support.
This flag configures IP broadcast support. This is useful only together with UDP.
Definition at line 217 of file uipopt.h.
#define UIP_BUFSIZE
The size of the uIP packet buffer.
The uIP packet buffer should not be smaller than 60 bytes, and does not need to be larger than 1514 bytes. Lower size results in lower TCP throughput, larger size results in higher TCP throughput.
Definition at line 173 of file uipopt.h.
Referenced by accept(), slip_send(), slipdev_poll(), and uip_send().
#define UIP_LLH_LEN
The link level header length.
This is the offset into the uip_buf where the IP header can be found. For Ethernet, this should be set to 14. For SLIP, this should be set to 0.
Note
we probably won't use this constant for other link layers than ethernet as they have variable header length (this is due to variable number and type of address fields and to optional security features) E.g.: 802.15.4 -> 2 + (1/2*4/8) + 0/5/6/10/14 802.11 -> 4 + (6*3/4) + 2
Definition at line 160 of file uipopt.h.
Referenced by ext_hdr_options_process(), input(), mac_ethernetToLowpan(), mac_LowpanToEthernet(), slide(), slip_send(), slipdev_poll(), slipdev_send(), uip_arp_out(), uip_fw_forward(), uip_ipchksum(), uip_process(), uip_send(), and uip_tcpchksum().
#define UIP_LOGGING
Determines if logging of certain events should be compiled in.
This is useful mostly for debugging. The function uip_log() must be implemented to suit the architecture of the project, if logging is turned on.
Definition at line 202 of file uipopt.h.
#define UIP_STATISTICS 0
Determines if statistics support should be compiled in.
The statistics is useful for debugging and to show the user.
Definition at line 187 of file uipopt.h.
Function Documentation
void uip_log (char * msg)
Print out a uIP log message.
This function must be implemented by the module that uses uIP, and is called by uIP whenever a log message is generated.
Definition at line 3 of file uip-log.c.
References addr, ADDR_TENTATIVE, clock_init(), CLOCK_SECOND, clock_wait(), count, ctimer_init(), etimer_request_poll(), uip_fw_netif::ipaddr, ipaddr, linkaddr_copy(), linkaddr_node_addr, linkaddr_set_node_addr(), main(), uip_fw_netif::netmask, NULL, process_init(), process_nevents(), process_run(), process_start(), program_handler_add(), random_init(), rtimer_init(), serial_line_input_byte(), slip_arch_init(), slip_set_input_callback(), timer_expired(), timer_reset(), timer_set(), timesynch_init(), timesynch_set_authority_level(), TRUE, uart0_init(), uart1_init(), uip_ds6_addr_add(), uip_ds6_set_addr_iid(), uip_fw_default(), uip_init(), uip_ip6addr, uip_ipaddr, uip_ipaddr_copy, uip_ipaddr_to_quad, uip_lladdr, UIP_LLADDR_LEN, UIP_NAMESERVER_INFINITE_LIFETIME, uip_nameserver_update(), uip_setdraddr, uip_sethostaddr, uip_setnetmask, uiplib_ipaddrconv, watchdog_periodic(), watchdog_start(), and watchdog_stop().