Contiki 3.x: Tree-based hop-by-hop reliable data collection
Tree-based hop-by-hop reliable data collection
Communication stacks » The Rime communication stack
The collect module implements a hop-by-hop reliable data collection mechanism.
Functions
static void send_queued_packet (struct collect_conn *c)
This function is called when a queued packet should be sent out.
static void retransmit_callback (void *ptr)
This function is called from a ctimer that is setup when a packet is sent.
static void retransmit_not_sent_callback (void *ptr)
This function is called from a ctimer that is setup when a packet is first transmitted.
static uint16_t rtmetric_compute (struct collect_conn *tc)
This function computes the current rtmetric by adding the last known rtmetric from our parent with the link estimate to the parent.
static void bump_advertisement (struct collect_conn *c)
This function is called when the route advertisements need to be transmitted more rapidly.
static void update_parent (struct collect_conn *tc)
This function is called to update the current parent node.
static void update_rtmetric (struct collect_conn *tc)
This function is called whenever there is a chance that the routing metric has changed.
static void retransmit_current_packet (struct collect_conn *c)
This function is called to retransmit the first packet on the send queue.
Detailed Description
The collect module implements a hop-by-hop reliable data collection mechanism.
Channels
The collect module uses 2 channels; one for neighbor discovery and one for data packets.
Function Documentation
static void retransmit_callback (void * ptr) static
This function is called from a ctimer that is setup when a packet is sent.
The purpose of this function is to either retransmit the current packet, or timeout the packet. The descision is made depending on how many times the packet has been transmitted. The ctimer is set up in the function node_packet_sent().
Definition at line 1184 of file collect.c.
References announcement_bump(), announcement_listen(), announcement_register(), announcement_remove(), announcement_set_value(), bump_advertisement(), CLOCK_SECOND, ctimer_set(), ctimer_stop(), linkaddr_copy(), linkaddr_node_addr, linkaddr_null, LIST_STRUCT_INIT, NULL, packetbuf_hdralloc(), packetqueue_dequeue(), packetqueue_enqueue_packetbuf(), packetqueue_first(), packetqueue_len(), random_rand(), retransmit_current_packet(), send_queued_packet(), and update_rtmetric().
Referenced by retransmit_current_packet(), and retransmit_not_sent_callback().
static void retransmit_not_sent_callback (void * ptr) static
This function is called from a ctimer that is setup when a packet is first transmitted.
If the MAC layer signals that the packet is sent, the ctimer will be stopped before this function is called. If this function ends up being called, we add the maximum number of MAC layer transmissions to the transmission count, and call the retransmit function.
Definition at line 1167 of file collect.c.
References retransmit_callback().
Referenced by update_rtmetric().
static void send_queued_packet (struct collect_conn * c) static
This function is called when a queued packet should be sent out.
The function takes the first packet on the output queue, adds the necessary packet attributes, and sends the packet to the next-hop neighbor.
Definition at line 569 of file collect.c.
References announcement_bump(), announcement_listen(), announcement_set_value(), ctimer_set(), linkaddr_copy(), linkaddr_node_addr, NULL, packetbuf_dataptr(), packetqueue_first(), and packetqueue_queuebuf().
Referenced by retransmit_callback(), retransmit_current_packet(), and update_rtmetric().
static void update_parent (struct collect_conn * tc) static
This function is called to update the current parent node.
The parent may change if new routing information has been found, for example if a new node with a lower rtmetric and link estimate has appeared.
Definition at line 285 of file collect.c.
References bump_advertisement(), linkaddr_cmp(), linkaddr_copy(), linkaddr_null, and NULL.
Referenced by update_rtmetric().
static void update_rtmetric (struct collect_conn * tc) static
This function is called whenever there is a chance that the routing metric has changed.
The function goes through the list of neighbors to compute the new routing metric. If the metric has changed, it notifies neighbors.
Definition at line 406 of file collect.c.
References announcement_set_value(), clock_time(), ctimer_set(), linkaddr_copy(), linkaddr_node_addr, list_head(), list_item_next(), NULL, packetbuf_clear(), packetbuf_hdralloc(), packetqueue_enqueue_packetbuf(), packetqueue_first(), retransmit_not_sent_callback(), rtmetric_compute(), send_queued_packet(), and update_parent().
Referenced by retransmit_callback(), and retransmit_current_packet().