Contiki 3.x: Rime addresses
Rime addresses
Communication stacks » The Rime communication stack
The linkaddr module is an abstract representation of addresses in Rime.
Functions
void linkaddr_copy (linkaddr_t *dest, const linkaddr_t *from)
Copy a Rime address.
int linkaddr_cmp (const linkaddr_t *addr1, const linkaddr_t *addr2)
Compare two Rime addresses.
void linkaddr_set_node_addr (linkaddr_t *addr)
Set the address of the current node.
Variables
linkaddr_t linkaddr_node_addr
The Rime address of the node.
linkaddr_t linkaddr_node_addr
The Rime address of the node.
const linkaddr_t linkaddr_null
The null Rime address.
Detailed Description
The linkaddr module is an abstract representation of addresses in Rime.
Function Documentation
int linkaddr_cmp (const linkaddr_t * addr1, const linkaddr_t * addr2)
Compare two Rime addresses.
Parameters
addr1 The first address
addr2 The second address
Returns
Non-zero if the addresses are the same, zero if they are different
        This function compares two Rime addresses and returns
        the result of the comparison. The function acts like
        the '==' operator and returns non-zero if the addresses
        are the same, and zero if the addresses are different.
Examples:
example-collect.c, example-multihop.c, example-runicast.c, and example-unicast.c.
Definition at line 69 of file linkaddr.c.
Referenced by find_handle(), mac_sequence_is_duplicate(), mac_sequence_register_seqno(), packetbuf_holds_broadcast(), retransmit_current_packet(), send_packet(), send_to_peer(), tsch_radio_off(), uip_ds6_nbr_add(), and update_parent().
void linkaddr_copy (linkaddr_t * dest, const linkaddr_t * from)
Copy a Rime address.
Parameters
dest The destination
from The source
        This function copies a Rime address from one location
        to another.
Examples:
example-collect.c, example-multihop.c, and example-runicast.c.
Definition at line 63 of file linkaddr.c.
Referenced by create_frame(), frame802154_parse(), linkaddr_set_node_addr(), mac_sequence_register_seqno(), output(), packetbuf_remaininglen(), retransmit_callback(), retransmit_current_packet(), send_packet(), send_queued_packet(), uip_log(), update_parent(), and update_rtmetric().
void linkaddr_set_node_addr (linkaddr_t * addr)
Set the address of the current node.
Parameters
addr The address
        This function sets the Rime address of the node.
Definition at line 75 of file linkaddr.c.
References linkaddr_copy(), and linkaddr_node_addr.
Referenced by main(), and uip_log().
Variable Documentation
linkaddr_t linkaddr_node_addr
The Rime address of the node.
This variable contains the Rime address of the node. This variable should not be changed directly; rather, the linkaddr_set_node_addr() function should be used.
Examples:
example-announcement.c, example-collect.c, example-multihop.c, example-rucb.c, example-rudolph1.c, example-rudolph2.c, example-runicast.c, example-trickle.c, and example-unicast.c.
Definition at line 48 of file linkaddr.c.
Referenced by abc_input(), abc_send(), ble_mac_ipsp_evt_handler_irq(), broadcast_send(), ipolite_send(), linkaddr_set_node_addr(), main(), mesh_send(), retransmit_callback(), retransmit_current_packet(), send_packet(), send_queued_packet(), shell_prompt(), tsch_radio_off(), tsch_security_secure_frame(), uip_log(), and update_rtmetric().
linkaddr_t linkaddr_node_addr
The Rime address of the node.
This variable contains the Rime address of the node. This variable should not be changed directly; rather, the linkaddr_set_node_addr() function should be used.
Definition at line 48 of file linkaddr.c.
const linkaddr_t linkaddr_null
The null Rime address.
This variable contains the null Rime address. The null address is used in route tables to indicate that the table entry is unused. Nodes with no configured address has the null address. Nodes with their node address set to the null address will have problems communicating with other nodes.
Examples:
example-collect.c, and example-unicast.c.
Definition at line 39 of file eth-conf.c.
Referenced by frame802154_parse(), output(), packetbuf_holds_broadcast(), packetbuf_remaininglen(), retransmit_callback(), send_to_peer(), tsch_radio_off(), uip_ds6_nbr_add(), and update_parent().