Contiki 3.x: CC13xx/CC26xx watchdog timer driver
CC13xx/CC26xx watchdog timer driver
Contiki platforms » TI CC26xx-powered Platforms » The TI CC26xx and CC13xx CPUs » CC13xx/CC26xx clock and timer subsystem
Driver for the CC13xx/CC26xx Watchdog Timer.
Files
file contiki-watchdog.c
Implementation of the CC13xx/CC26xx watchdog driver.
Functions
void watchdog_init (void)
Initialises the CC26xx WDT.
void watchdog_start (void)
Starts the CC26xx WDT.
void watchdog_periodic (void)
Refreshes the CC26xx WDT.
void watchdog_stop (void)
Stops the WDT such that it won't timeout and cause MCU reset.
void watchdog_reboot (void)
Manually trigger a WDT reboot.
Detailed Description
Driver for the CC13xx/CC26xx Watchdog Timer.
This file is not called watchdog.c because the filename is in use by TI CC26xxware/CC13xxware
Function Documentation
void watchdog_init (void)
Initialises the CC26xx WDT.
Copyright (c) 2014, Analog Devices, Inc.
Simply sets the reload counter to a default value. The WDT is not started yet. To start it, watchdog_start() must be called.
Definition at line 108 of file contiki-watchdog.c.
void watchdog_periodic (void)
Refreshes the CC26xx WDT.
Writes the WDT clear sequence.
Definition at line 132 of file contiki-watchdog.c.
Referenced by watchdog_start().
void watchdog_reboot (void)
Manually trigger a WDT reboot.
Keeps control until the WDT throws a reset signal.
Definition at line 155 of file contiki-watchdog.c.
References watchdog_start().
void watchdog_start (void)
Starts the CC26xx WDT.
Starts the WDT in watchdog mode if enabled by user configuration, maximum interval.
Definition at line 118 of file contiki-watchdog.c.
References watchdog_periodic().
Referenced by watchdog_reboot().