Contiki 3.x: nRF52 Development Kit
nRF52 Development Kit
Contiki platforms
Modules
nRF52 SDK configuration
Contiki configuration
Platform configuration
Debug IO over UART
Device drivers
Functions
static void board_init (void)
Board specific initialization.
int main (void)
Main function for nRF52dk platform.
Detailed Description
Function Documentation
static void board_init (void) static
Board specific initialization.
This function will enable SoftDevice is present.
Definition at line 110 of file contiki-main.c.
References NULL.
Referenced by main().
int main (void)
Main function for nRF52dk platform.
This is main...
Note
This function doesn't return.
Definition at line 128 of file contiki-main.c.
References ble_advertising_init(), ble_advertising_start(), ble_get_mac(), ble_stack_init(), board_init(), clock_init(), ctimer_init(), DEVICE_NAME, linkaddr_set_node_addr(), lpm_drop(), NULL, process_init(), process_run(), process_start(), random_init(), rtimer_init(), serial_line_input_byte(), slip_arch_init(), uart0_init(), uip_lladdr, watchdog_init(), watchdog_periodic(), and watchdog_start().