Contiki 3.x: Serial interface between Raven processors
Serial interface between Raven processors
Contiki platforms » AVR-ATMEGA128RFA1 platformContiki platforms » | Atmel AVR Raven
This module contains code to interface a Contiki-based project on the AVR Raven platform's ATMega1284P chip to the LCD driver chip (ATMega3290P) on the Raven.
Files
file raven-ipso.c
This file contains code to connect the two AVR Raven processors via a serial connection for the IPSO interop application.
file raven-lcd.c
This file contains code to connect the two AVR Raven processors via a serial connection.
file raven-ipso.c
This file contains code to connect the two AVR Raven processors via a serial connection for the IPSO interop application.
file raven-lcd.c
This file contains code to connect the two AVR Raven processors via a serial connection.
Functions
void rs232_send (uint8_t port, unsigned char c)
Print a character on RS232.
Detailed Description
This module contains code to interface a Contiki-based project on the AVR Raven platform's ATMega1284P chip to the LCD driver chip (ATMega3290P) on the Raven.
Author
Durvy Mathilde mdurv.nosp@m.y@ci.nosp@m.sco.c.nosp@m.om
Blake Leverett bleve.nosp@m.rett.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Blake Leverett bleve.nosp@m.rett.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Cristiano De Alti crist.nosp@m.iano.nosp@m._deal.nosp@m.ti@h.nosp@m.otmai.nosp@m.l.co.nosp@m.m
Function Documentation
void rs232_send (uint8_t port, unsigned char c)
Print a character on RS232.
Parameters
port The RS232 port to be used.
c The character to be printed
        This function prints a character to RS232. The RS232
        module must be correctly initalized and configured for
        this function to work.
Definition at line 325 of file rs232.c.
References NULL, rs232_print(), rs232_send(), rs232_set_input(), and slip_arch_writeb().
Referenced by rs232_send().