Contiki 3.x: CC13xx/CC26xx AON RTC driver
CC13xx/CC26xx AON RTC driver
Contiki platforms » TI CC26xx-powered Platforms » The TI CC26xx and CC13xx CPUs » CC13xx/CC26xx clock and timer subsystem
Underpins the platform's software clocks and timers.
Files
file soc-rtc.c
Implementation of the CC13xx/CC26xx AON RTC driver.
file soc-rtc.h
Header file for the CC13xx/CC26xx AON RTC driver.
Functions
void soc_rtc_init (void)
Initialise the CC13XX/CC26XX AON RTC module.
rtimer_clock_t soc_rtc_get_next_trigger (void)
Return the time of the next scheduled rtimer event.
void soc_rtc_schedule_one_shot (uint32_t channel, uint32_t t)
Schedule an AON RTC channel 0 one-shot compare event.
Detailed Description
Underpins the platform's software clocks and timers.
Function Documentation
rtimer_clock_t soc_rtc_get_next_trigger (void)
Return the time of the next scheduled rtimer event.
Returns
The time at which the next rtimer event is due to fire
This function will check both AON RTC channels and will only take CH0's compare into account if the channel is actually enabled
Definition at line 112 of file soc-rtc.c.
void soc_rtc_init (void)
Initialise the CC13XX/CC26XX AON RTC module.
This timer configures AON RTC channels.
This function must be called before clock_init() and rtimer_init()
Definition at line 72 of file soc-rtc.c.
Referenced by main().
void soc_rtc_schedule_one_shot (uint32_t channel, uint32_t t)
Schedule an AON RTC channel 0 one-shot compare event.
Parameters
channel AON_RTC_CH0 or AON_RTC_CH1
t The time when the event will be fired. This is an absolute time, in other words the event will fire AT time t, not IN t ticks
Channel AON_RTC_CH0 is reserved for the rtimer. AON_RTC_CH1 is reserved for the system clock.
User applications should not use this function. User applications should instead use Contiki's timer-related libraries
Definition at line 126 of file soc-rtc.c.
References RTIMER_NOW, and rtimer_run_next().
Referenced by lpm_shutdown(), and rtimer_arch_schedule().