Contiki 3.x: SmartRF+CC13xx/CC26xx EM, SensorTags and LaunchPads
SmartRF+CC13xx/CC26xx EM, SensorTags and LaunchPads
Contiki platforms » TI CC26xx-powered Platforms
This platform supports a number of different boards:
Modules
CC13xx/CC26xx peripheral driver pool
Drivers for peripherals present on more than one CC13xx/CC26xx board.
LaunchPad peripherals
Defines related to LaunchPad peripherals.
Sensortag CC1350/CC2650 common
Defines related to Sensortag sensors.
CC1350 Sensortag Peripherals
Defines related to the CC1350 Sensortag.
CC2650 Sensortag Peripherals
Defines related to the CC2650 Sensortag.
SmartRF06EB + CC13xx/CC26xx common
Defines related to the SmartRF06 Evaluation Board irrespective of the EM mounted on it.
Peripherals for the SmartRF06EB + CC1310EM
Defines related to the SmartRF06 Evaluation Board with a CC1310EM.
Peripherals for the SmartRF06EB + CC26xxEM
Defines related to the SmartRF06 Evaluation Board with a CC26xxEM.
Files
file contiki-conf.h
Configuration for the srf06-cc26xx platform.
Functions
void board_init (void)
Board specific iniatialisation.
int main (void)
Main function for CC26xx-based platforms.
Network Stack Configuration
#define NETSTACK_CONF_NETWORK sicslowpan_driver
#define NETSTACK_CONF_MAC csma_driver
#define NETSTACK_CONF_RDC contikimac_driver
#define CC2650_FAST_RADIO_STARTUP 0
#define NULLRDC_CONF_802154_AUTOACK 1
#define CONTIKIMAC_CONF_WITH_CONTIKIMAC_HEADER 0
#define CONTIKIMAC_CONF_WITH_PHASE_OPTIMIZATION 0
#define WITH_FAST_SLEEP 1
#define NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE 8
#define NETSTACK_CONF_FRAMER framer_802154
#define PROP_MODE_CONF_RX_BUF_CNT 4
#define NETSTACK_CONF_RADIO ieee_mode_driver
#define RF_CORE_CONF_CHANNEL 25
#define NULLRDC_CONF_802154_AUTOACK_HW 1
#define NULLRDC_CONF_SEND_802154_ACK 0
#define NETSTACK_RADIO_MAX_PAYLOAD_LEN 125
#define SICSLOWPAN_CONF_COMPRESSION SICSLOWPAN_COMPRESSION_HC06
#define SICSLOWPAN_CONF_COMPRESSION_THRESHOLD 63
#define SICSLOWPAN_CONF_FRAG 1
#define SICSLOWPAN_CONF_MAXAGE 8
IEEE address configuration
Used to generate our RIME & IPv6 address
#define IEEE_ADDR_CONF_HARDCODED 0
Location of the IEEE address 0 => Read from InfoPage, 1 => Use a hardcoded address, configured by IEEE_ADDR_CONF_ADDRESS.
#define IEEE_ADDR_CONF_ADDRESS { 0x00, 0x12, 0x4B, 0x00, 0x89, 0xAB, 0xCD, 0xEF }
The hardcoded IEEE address to be used when IEEE_ADDR_CONF_HARDCODED is defined as 1.
RF configuration
#define IEEE802154_CONF_PANID 0xABCD
Default PAN ID.
#define IEEE_MODE_CONF_AUTOACK 1
RF H/W generates ACKs.
#define IEEE_MODE_CONF_PROMISCOUS 0
1 to enable promiscous mode
#define RF_BLE_CONF_ENABLED 0
0 to disable BLE support
Detailed Description
This platform supports a number of different boards:
A standard TI SmartRF06EB with a CC26xx EM mounted on it
A standard TI SmartRF06EB with a CC1310 EM mounted on it
The TI CC2650 SensorTag
The TI CC1350 SensorTag
The TI CC2650 LaunchPad
The TI CC1310 LaunchPad
The TI CC1350 LaunchPad
Function Documentation
int main (void)
Main function for CC26xx-based platforms.
This is main...
The same main() is used for all supported boards
Definition at line 144 of file contiki-main.c.
References board_init(), cc26xx_uart_init(), clock_init(), ctimer_init(), gpio_interrupt_init(), LEDS_ORANGE, linkaddr_node_addr, lpm_drop(), lpm_init(), NULL, oscillators_select_lf_xosc(), process_init(), process_run(), process_start(), random_init(), rtimer_init(), soc_rtc_init(), uip_lladdr, watchdog_init(), watchdog_periodic(), and watchdog_start().