Contiki 3.x: CC13xx/CC26xx Character I/O
CC13xx/CC26xx Character I/O
Contiki platforms » TI CC26xx-powered Platforms » The TI CC26xx and CC13xx CPUs
CC13xx/CC26xx CPU-specific functions for debugging and SLIP I/O.
Files
file dbg.h
Header file for the CC13xx/CC26xx Debug I/O module.
file debug-uart.h
This file is here because DBG I/O expects it to be.
file slip-arch.c
Arch-specific SLIP functions for the CC13xx/CC26xx.
Functions
unsigned int dbg_send_bytes (const unsigned char *seq, unsigned int len)
Print a stream of bytes.
void slip_arch_writeb (unsigned char c)
Write a byte over SLIP.
void slip_arch_init (unsigned long ubr)
Initialise the arch-specific SLIP driver.
Detailed Description
CC13xx/CC26xx CPU-specific functions for debugging and SLIP I/O.
Function Documentation
unsigned int dbg_send_bytes (const unsigned char * seq, unsigned int len)
Print a stream of bytes.
Parameters
seq A pointer to the stream
len The number of bytes to print
Returns
The number of printed bytes
This function is an arch-specific implementation required by the dbg-io API in cpu/arm/common/dbg-io. It prints a stream of bytes over the peripheral used by the platform.
Parameters
seq A pointer to the stream
len The number of bytes to print
Returns
The number of printed bytes
This function is an arch-specific implementation required by the dbg-io API in cpu/arm/common/dbg-io. It prints a stream of bytes over the peripheral used by the platform.
Parameters
seq A pointer to the stream
len The number of bytes to print
Returns
The number of printed bytes
Parameters
seq A pointer to the stream
len The number of bytes to print
Returns
The number of printed bytes
This function is an arch-specific implementation required by the dbg-io API in cpu/arm/common/dbg-io. It prints a stream of bytes over the peripheral used by the platform.
Parameters
seq A pointer to the stream
len The number of bytes to print
Returns
The number of printed bytes
Parameters
seq A pointer to the stream
len The number of bytes to print
Returns
The number of printed bytes
This function is an arch-specific implementation required by the dbg-io API in cpu/arm/common/dbg-io. It prints a stream of bytes over the peripheral used by the platform.
Parameters
seq A pointer to the stream
len The number of bytes to print
Returns
The number of printed bytes
Definition at line 71 of file debug-uart.c.
void slip_arch_init (unsigned long ubr)
Initialise the arch-specific SLIP driver.
Initalize the RS232 port and the SLIP driver.
Parameters
ubr Ignored for the cc26xx
Definition at line 59 of file slip-arch.c.
References cc26xx_uart_set_input(), and slip_input_byte().
void slip_arch_writeb (unsigned char c)
Write a byte over SLIP.
Copyright (c) 2014, Analog Devices, Inc.
Parameters
c the byte
Definition at line 49 of file slip-arch.c.
References cc26xx_uart_write_byte().