Contiki 3.x: MRF24J40 Driver
MRF24J40 Driver
Contiki platforms » Contiki SEEDEYE Platform
Files
file mrf24j40.c
MRF24J40 Driver.
file mrf24j40.h
MRF24J40 Driver.
file mrf24j40_arch.h
MRF24J40 Specific Arch Conf.
Functions
void mrf24j40_set_channel (uint16_t ch)
Set the channel.
void mrf24j40_set_panid (uint16_t id)
Store MAC PAN ID.
void mrf24j40_set_short_mac_addr (uint16_t addr)
Store short MAC address.
void mrf24j40_set_extended_mac_addr (uint64_t addr)
Store extended MAC address.
void mrf24j40_get_short_mac_addr (uint16_t *addr)
Get short MAC address.
void mrf24j40_get_extended_mac_addr (uint64_t *addr)
Gets extended MAC address.
void mrf24j40_set_tx_power (uint8_t pwr)
Set TX power.
uint8_t mrf24j40_get_status (void)
Get radio status.
uint8_t mrf24j40_get_rssi (void)
Get the RSSI.
uint8_t mrf24j40_get_last_rssi (void)
Get the last read RSSI.
uint8_t mrf24j40_get_last_lqi (void)
Get the last read LQI.
int32_t mrf24j40_set_txfifo (const uint8_t *buf, uint8_t buf_len)
Store message.
int32_t mrf24j40_get_rxfifo (uint8_t *buf, uint8_t buf_len)
Get message.
static void put_to_sleep (void)
Start sleep.
static void wake (void)
Awake the radio.
int mrf24j40_init (void)
Init transceiver.
Detailed Description
Function Documentation
void mrf24j40_get_extended_mac_addr (uint64_t * addr)
Gets extended MAC address.
This routine gets the extended MAC address stored in the MRF24J40.
Definition at line 270 of file mrf24j40.c.
uint8_t mrf24j40_get_last_lqi (void)
Get the last read LQI.
This routine returns the last lqi
Definition at line 367 of file mrf24j40.c.
uint8_t mrf24j40_get_last_rssi (void)
Get the last read RSSI.
This routine returns the last rssi value mesured in dbm Note: to convert the returned value to dBm, use the table 3-8 available in the MRF24J40 datasheet.
Definition at line 356 of file mrf24j40.c.
uint8_t mrf24j40_get_rssi (void)
Get the RSSI.
This routine returns the rssi value mesured in dbm Note: to convert the returned value to dBm, use the table 3-8 available in the MRF24J40 datasheet.
Definition at line 313 of file mrf24j40.c.
Referenced by mrf24j40_init().
int32_t mrf24j40_get_rxfifo (uint8_t * buf, uint8_t buf_len)
Get message.
This routine is used to retrieve a message stored in the RX_FIFO
Definition at line 404 of file mrf24j40.c.
Referenced by mrf24j40_init().
void mrf24j40_get_short_mac_addr (uint16_t * addr)
Get short MAC address.
This routine gets the short MAC address stored in the MRF24J40.
Definition at line 258 of file mrf24j40.c.
uint8_t mrf24j40_get_status (void)
Get radio status.
This routine returns the MRF24J40 status.
Definition at line 299 of file mrf24j40.c.
int mrf24j40_init (void)
Init transceiver.
This routine initializes the radio transceiver
Definition at line 524 of file mrf24j40.c.
References clock_delay_usec(), radio_driver::get_object, radio_driver::get_value, int_status(), mrf24j40_get_rssi(), mrf24j40_get_rxfifo(), mrf24j40_set_channel(), mrf24j40_set_tx_power(), mrf24j40_set_txfifo(), NULL, packetbuf_clear(), packetbuf_dataptr(), packetbuf_set_datalen(), PACKETBUF_SIZE, PROCESS_BEGIN, PROCESS_END, process_poll(), process_start(), PROCESS_THREAD, PROCESS_YIELD_UNTIL, radio_driver::set_object, and radio_driver::set_value.
void mrf24j40_set_channel (uint16_t ch)
Set the channel.
This routine sets the rx/tx channel
Definition at line 203 of file mrf24j40.c.
Referenced by mrf24j40_init().
void mrf24j40_set_extended_mac_addr (uint64_t addr)
Store extended MAC address.
This routine sets the extended MAC address in the MRF24J40.
Definition at line 240 of file mrf24j40.c.
void mrf24j40_set_panid (uint16_t id)
Store MAC PAN ID.
This routine sets the MAC PAN ID in the MRF24J40.
Definition at line 216 of file mrf24j40.c.
void mrf24j40_set_short_mac_addr (uint16_t addr)
Store short MAC address.
This routine sets the short MAC address in the MRF24J40.
Definition at line 228 of file mrf24j40.c.
void mrf24j40_set_tx_power (uint8_t pwr)
Set TX power.
This routine sets the transmission power of the MRF24J40.
Definition at line 288 of file mrf24j40.c.
Referenced by mrf24j40_init().
int32_t mrf24j40_set_txfifo (const uint8_t * buf, uint8_t buf_len)
Store message.
This routine stores a buffer of buf_len bytes in the TX_FIFO buffer of the MRF24J40.
Definition at line 379 of file mrf24j40.c.
Referenced by mrf24j40_init().
static void put_to_sleep (void) static
Start sleep.
This routine puts the radio in sleep mode.
Definition at line 457 of file mrf24j40.c.
Referenced by wake().
static void wake (void) static
Awake the radio.
This routine turns on and sets the radio on receiving mode. Note: After performing this routine the radio is in the receiving state.
Definition at line 480 of file mrf24j40.c.
References clock_delay_usec(), and put_to_sleep().
Referenced by ieee_15_4_init().