Contiki 3.x: Hardware random number generator
Hardware random number generator
Contiki CPUs » nRF52832 » Device drivers
Files
file random.c
Random number generator routines exploiting the nRF52 hardware capabilities.
Functions
unsigned short random_rand (void)
Generates a new random number using the nRF52 RNG.
void random_init (unsigned short seed)
Initialize the nRF52 random number generator.
Detailed Description
Function Documentation
void random_init (unsigned short seed)
Initialize the nRF52 random number generator.
Seed the cc2538 random number generator.
Parameters
seed Ignored. It's here because the function prototype is in core.
Definition at line 80 of file random.c.
References NULL.
Referenced by main(), and uip_log().
unsigned short random_rand (void)
Generates a new random number using the nRF52 RNG.
Generates a new random number using the cc2538 RNG.
Returns
a random number.
Definition at line 58 of file random.c.
Referenced by create_frame(), ipolite_send(), polite_send(), resolv_get_hostname(), retransmit_callback(), retransmit_current_packet(), send_packet(), servreg_hack_lookup(), servreg_hack_register(), uip_ds6_addr_add(), uip_ds6_compute_reachable_time(), uip_ds6_dad_failed(), and uip_ds6_init().