Contiki 3.x: Debug IO over UART
Debug IO over UART
Contiki platforms » nRF52 Development Kit
Files
file dbg.c
Function implementations for debug io module.
file dbg.h
Header file for the debug module.
file debug-uart.h
A header file to maintain compatibility with DBG I/O.
Functions
unsigned int dbg_send_bytes (const unsigned char *seq, unsigned int len)
Print a stream of bytes.
int dbg_putchar (int c)
Print a character to debug output.
Detailed Description
Function Documentation
int dbg_putchar (int c)
Print a character to debug output.
Parameters
c Character to print
Returns
Printed character
Definition at line 63 of file dbg.c.
Referenced by dbg_send_bytes().
unsigned int dbg_send_bytes (const unsigned char * seq, unsigned int len)
Print a stream of bytes.
Parameters
seq A pointer to the stream
len The number of bytes to print
Returns
The number of printed bytes
Definition at line 47 of file dbg.c.
References dbg_putchar(), dbg_send_bytes(), and NULL.