Contiki 3.x: Temperature sensor driver
Temperature sensor driver
Contiki platforms » nRF52 Development Kit » Device drivers
This is a driver for nRF52832 hardware sensor.
Files
file temperature-sensor.c
Temperature sensor implementation.
file temperature-sensor.h
Temperature sensor header file.
Functions
static int value (int type)
Returns device temperature.
static int configure (int type, int c)
Configures temperature sensor.
static int status (int type)
Return temperature sensor status.
Variables
const struct sensors_sensor temperature_sensor
NOTE: For the temperature measurement, the ADC extended range mode is needed; but this is inaccurate due to the high voltage mode bug of the general purpose ADC (see STM32W108 errata).
const struct sensors_sensor temperature_sensor
NOTE: For the temperature measurement, the ADC extended range mode is needed; but this is inaccurate due to the high voltage mode bug of the general purpose ADC (see STM32W108 errata).
Detailed Description
This is a driver for nRF52832 hardware sensor.
Function Documentation
static int configure (int type, int c) static
Configures temperature sensor.
Parameters
type initializes the hardware sensor when type is set to SENSORS_HW_INIT
c ignored
Returns
1
Note
This function does nothing when SoftDevice is present
Definition at line 84 of file temperature-sensor.c.
Referenced by status().
static int status (int type) static
Return temperature sensor status.
Parameters
type ignored
Returns
1
Definition at line 100 of file temperature-sensor.c.
References configure(), temperature_sensor, and value().
static int value (int type) static
Returns device temperature.
Parameters
type ignored
Returns
Device temperature in degrees Celsius
Definition at line 64 of file temperature-sensor.c.
Referenced by status().