Contiki 3.x: XgNicLanc111
XgNicLanc111
Contiki CPUs » AVR » SMSC Registers
Functions
static uint16_t NicPhyRead (uint8_t reg)
Read contents of PHY register.
static void NicPhyWrite (uint8_t reg, uint16_t val)
Write value to PHY register.
static int NicPhyConfig (void)
Configure the internal PHY.
static INLINE int NicMmuWait (uint16_t tmo)
Wait until MMU is ready.
static int NicReset (void)
Reset the Ethernet controller.
static NETBUF * NicGetPacket (void)
Fetch the next packet out of the receive ring buffer.
Variables
static struct etimer et
NIC receiver thread.
Detailed Description
Function Documentation
static NETBUF* NicGetPacket (void) static
Fetch the next packet out of the receive ring buffer.
Nic interrupts must be disabled when calling this funtion.
Returns
Pointer to an allocated NETBUF. If there is no no data available, then the function returns a null pointer. If the NIC's buffer seems to be corrupted, a pointer to 0xFFFF is returned.
Definition at line 960 of file lanc111.c.
References INT_ALLOC, INT_TX, INT_TX_EMPTY, NIC_DATA, NIC_FIFO, NIC_IST, NIC_MMUCR, NIC_MSK, NIC_PNR, NIC_PTR, NicMmuWait(), and PROCESS_THREAD.
static INLINE int NicMmuWait (uint16_t tmo) static
Wait until MMU is ready.
Poll the MMU command register until MMUCR_BUSY is cleared.
Parameters
tmo Timeout in milliseconds.
Returns
0 on success or -1 on timeout.
Definition at line 742 of file lanc111.c.
References MMUCR_BUSY, and NIC_MMUCR.
Referenced by NicGetPacket(), and NicReset().
static int NicPhyConfig (void) static
Configure the internal PHY.
Reset the PHY and initiate auto-negotiation.
Definition at line 650 of file lanc111.c.
References NIC_PHYANAD, NIC_PHYCFR1, NIC_PHYCR, NIC_PHYMSK, NIC_PHYSOR, NIC_PHYSR, NIC_RPCR, NicPhyRead(), NicPhyWrite(), PHYANAD_10_HDX, PHYANAD_10FDX, PHYANAD_CSMA, PHYANAD_TX_FDX, PHYANAD_TX_HDX, PHYCR_ANEG_EN, PHYCR_ANEG_RST, PHYCR_RST, PHYMSK_MCWRD, PHYMSK_MDPLDT, PHYMSK_MESD, PHYMSK_MJAB, PHYMSK_MLOSSSYN, PHYMSK_MRPOL, PHYMSK_MSPDDT, PHYMSK_MSSD, PHYSR_ANEG_ACK, RPCR_ANEG, RPCR_LEDA_PAT, and RPCR_LEDB_PAT.
Referenced by NicReset().
static uint16_t NicPhyRead (uint8_t reg) static
Read contents of PHY register.
Note
NIC interrupts must have been disabled before calling this routine.
Parameters
reg PHY register number.
Returns
Contents of the specified register.
Definition at line 580 of file lanc111.c.
References MGMT_MCLK, MGMT_MDI, MGMT_MDOE, NIC_MGMT, and NicPhyRegSelect().
Referenced by NicPhyConfig().
static void NicPhyWrite (uint8_t reg, uint16_t val) static
Write value to PHY register.
Note
NIC interrupts must have been disabled before calling this routine.
Parameters
reg PHY register number.
val Value to write.
Definition at line 616 of file lanc111.c.
References MGMT_MCLK, MGMT_MDO, MGMT_MDOE, NIC_MGMT, and NicPhyRegSelect().
Referenced by NicPhyConfig().
static int NicReset (void) static
Reset the Ethernet controller.
Returns
0 on success, -1 otherwise.
Definition at line 757 of file lanc111.c.
References CR_EPH_EN, CTR_AUTO_RELEASE, INT_ALLOC, INT_ERCV, INT_RCV, INT_RX_OVRN, INT_TX, INT_TX_EMPTY, NIC_ACK, NIC_CR, NIC_CTR, NIC_DATA, NIC_ERCV, NIC_IAR, NIC_IST, NIC_MMUCR, NIC_MSK, NIC_RCR, NIC_TCR, NicMmuWait(), NicPhyConfig(), RCR_RXEN, RCR_SOFT_RST, TCR_PAD_EN, and TCR_TXENA.